spring:

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        observation-enabled: true
      template:
        observation-enabled: true

  app:
    rabbitmq:
      exchange-name: payment-state-check-exchange
      delayed-exchange-name: payment-state-check-exchange
      dlx-exchange-name: payment.dlx
      dlx-routing-key: payment.dead
      queue-name: payment-state-check-queue
      max-retries: 60
      interval-ms: 60000
